# Generated by Django 4.1.3 on 2023-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=500)),
                ('phoneno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
