# Generated by Django 4.1.3 on 2023-01-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_contact_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneno',
            field=models.IntegerField(default=0),
        ),
    ]
