# Generated by Django 4.1.3 on 2023-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_contact_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneno',
            field=models.CharField(default='', max_length=500),
        ),
    ]
