# Generated by Django 4.1.3 on 2023-01-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
